spring:
  mail:
    port: 465
    host: smtp.qq.com
    username: 898469219@qq.com
    password: qktzofbzolcybcjb
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true